EXEC altaServicio @nombre='Resonancia magnetica', @tipo='MR'
EXEC altaServicio @nombre='Laboratorio', @tipo='LA'
EXEC altaServicio @nombre='Consulta médica', @tipo='CM'
EXEC altaServicio @nombre='Guardia', @tipo='GD'
EXEC altaServicio @nombre='Rayos', @tipo='RY'