insert into HorariosDisponib (id_servicio_profesional, es_profesional, fecha_hora_inicio, fecha_hora_fin) values (1, 1, getdate(), dateadd(hh,1, getdate()))
insert into HorariosDisponib (id_servicio_profesional, es_profesional, fecha_hora_inicio, fecha_hora_fin) values (1, 1, dateadd(hh, 1, getdate()), dateadd(hh, 2, getdate()))
insert into HorariosDisponib (id_servicio_profesional, es_profesional, fecha_hora_inicio, fecha_hora_fin) values (1, 1, dateadd(hh, 2, getdate()), dateadd(hh, 3, getdate()))
insert into HorariosDisponib (id_servicio_profesional, es_profesional, fecha_hora_inicio, fecha_hora_fin) values (2, 1, getdate(), dateadd(hh,1, getdate()))
insert into HorariosDisponib (id_servicio_profesional, es_profesional, fecha_hora_inicio, fecha_hora_fin) values (2, 1, dateadd(hh, 1, getdate()), dateadd(hh, 2, getdate()))
insert into HorariosDisponib (id_servicio_profesional, es_profesional, fecha_hora_inicio, fecha_hora_fin) values (2, 1, dateadd(hh, 1, getdate()), dateadd(hh, 2, getdate()))
insert into HorariosDisponib (id_servicio_profesional, es_profesional, fecha_hora_inicio, fecha_hora_fin) values (3, 1, getdate(), dateadd(hh,1, getdate()))
insert into HorariosDisponib (id_servicio_profesional, es_profesional, fecha_hora_inicio, fecha_hora_fin) values (3, 1, dateadd(hh, 1, getdate()), dateadd(hh, 2, getdate()))
insert into HorariosDisponib (id_servicio_profesional, es_profesional, fecha_hora_inicio, fecha_hora_fin) values (3, 1, dateadd(hh, 1, getdate()), dateadd(hh, 2, getdate()))

insert into HorariosDisponib (id_servicio_profesional, es_profesional, fecha_hora_inicio, fecha_hora_fin) values (1, 0, getdate(), dateadd(hh,5, getdate()))
insert into HorariosDisponib (id_servicio_profesional, es_profesional, fecha_hora_inicio, fecha_hora_fin) values (2, 0, getdate(), dateadd(hh,5, getdate()))
insert into HorariosDisponib (id_servicio_profesional, es_profesional, fecha_hora_inicio, fecha_hora_fin) values (3, 0, getdate(), dateadd(hh,5, getdate()))